# Generated by Django 4.2.30 on 2026-05-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pgn", models.TextField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("draw", "Draw"),
                            ("resigned", "Resigned"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "AI")], max_length=10
                    ),
                ),
                ("ai_level", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analysis", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
