# Generated by Django 4.2.30 on 2026-05-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_friendship"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="friendship",
            options={"ordering": ["-created_at"]},
        ),
    ]
